### ISSUE TITLE
 not support to start history server

### ISSUE THREAD

**Issue by 0neday** [bitnami/bitnami-docker-spark#50]
```
I have no name!@c78d0cb4b51f:/opt/bitnami/spark$ ./sbin/start-history-server.sh 
starting org.apache.spark.deploy.history.HistoryServer, logging to /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.history.HistoryServer-1-c78d0cb4b51f.out
failed to launch: nice -n 0 /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer
        at org.apache.spark.deploy.history.FsHistoryProvider.start(FsHistoryProvider.scala:413)
        at org.apache.spark.deploy.history.HistoryServer$.main(HistoryServer.scala:306)
        at org.apache.spark.deploy.history.HistoryServer.main(HistoryServer.scala)
  Caused by: java.io.FileNotFoundException: File file:/tmp/spark-events does not exist
```

**Comment by miguelaeh** [comment]
Hi @0neday ,
Could you please add more information, please?

**Comment by alvneiayu** [comment]
hi @0neday 

The reason of the error is that the container by default doesn't have the folder "/tmp/spark-events". You have several options to do a workaround:

- Create manually the folder inside the container (mkdir /tmp/spark-events).
- Include a volume inside the dockerfile:
```
diff --git a/3/debian-10/docker-compose.yml b/3/debian-10/docker-compose.yml
index 48e7e57..50e4151 100644
--- a/3/debian-10/docker-compose.yml
+++ b/3/debian-10/docker-compose.yml
@@ -11,6 +11,8 @@ services:
       - SPARK_SSL_ENABLED=no
     ports:
       - '8080:8080'
+    volumes:
+      - ./spark-events:/tmp/spark-events
   spark-worker-1:
     image: docker.io/bitnami/spark:3
     environment:
```
- Create the folder using the Dockerfile:
```
RUN mkdir -p /tmp/spark-events
```
- Modify the Spark default configuration to use another folder:
```
spark.eventLog.dir              file:/another-folder-path
```

Let me know if you can fix your problem doing one of the options.

Thanks a lot

Álvaro

**Comment by 0neday** [comment]
thank you @alvneiayu, I have fixed, using hdfs.
```
spark.eventLog.enabled         true
spark.eventLog.dir                 hdfs://spark:8021/user/root/spark-events
spark.history.fs.logDirectory  hdfs://spark:8021/user/root/spark-events
```
need to start hdfs using hadoop.
check [here](https://segmentfault.com/a/1190000014974857)
