### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException: /opt/bitnami/spark/.ivy2/cache/

### ISSUE THREAD

**Issue by rightx2** [bitnami/bitnami-docker-spark#59]
**Description**

`Exception in thread "main" java.io.FileNotFoundException: /opt/bitnami/spark/.ivy2/cache/`

**Steps to reproduce the issue:**

1. git clone `git@github.com:udacity/nd029-c2-apache-spark-and-spark-streaming-starter.git`
2. Copy `docker-compose.yml` file from the [link](https://gist.github.com/rightx2/00bf6a6ff00f63997de429d6f8ac7770) and replace the original `docker-compose.yml` in the repo 
    - What's the difference with the original one? Changing spark version and some volume mounts. The reason will be mentioned at **Additional information you deem important** section.
3. `docker-compose up -d`
4. `docker-compose exec spark-worker-1 /bin/bash`
5. `vi /home/workspace/lesson-1-streaming-dataframes/exercises/starter/atm-visits.py`
```python
from pyspark.sql import SparkSession

# the source for this data pipeline is a kafka topic, defined below
spark = SparkSession.builder.appName("atm-visits").getOrCreate()
spark.sparkContext.setLogLevel("WARN")

atmVisitsRawStreamingDF = (
    spark.readStream
    .format("kafka")
    .option("kafka.bootstrap.servers", "localhost:9092")
    .option("subscribe", "atm-visits")
    .option("startingOffsets", "earliest")
    .load()
)
```
6.  `spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.1 /home/workspace/lesson-1-streaming-dataframes/exercises/starter/atm-visits.py`

**Describe the results you received:**

```
Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
:: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-c42717bb-68ca-4ff9-984e-5a32c519fbc3;1.0
    confs: [default]
Exception in thread "main" java.io.FileNotFoundException: /opt/bitnami/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-c42717bb-68ca-4ff9-984e-5a32c519fbc3-1.0.xml (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:70)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:62)
    at org.apache.ivy.core.module.descriptor.DefaultModuleDescriptor.toIvyFile(DefaultModuleDescriptor.java:563)
    at org.apache.ivy.core.cache.DefaultResolutionCacheManager.saveResolvedModuleDescriptor(DefaultResolutionCacheManager.java:176)
    at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:245)
    at org.apache.ivy.Ivy.resolve(Ivy.java:523)
    at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1387)
    at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
    at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:871)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
I have no name!@b36e64373639:/opt/bitnami/spark$
```

**Describe the results you expected:**

Spark job submitted and work without any errors

**Additional information you deem important (e.g. issue happens only occasionally):**

After googling, I've found out some solutions:
- https://stackoverflow.com/questions/60630832/i-cannot-use-package-option-on-bitnami-spark-docker-container
- https://github.com/bitnami/bitnami-docker-spark/issues/7
- https://www.python2.net/questions-1842098.htm

and edited `docker-compose.yml` file according to them but still doesn't work.(Looks like these solution are for spark v2.x)

Is there anything I can do to solve this problem?

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 37
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-38-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 46.99GiB
 Name: gpu1
 ID: ORTM:RC4R:5PNV:HCL3:CKFD:KIAN:VANZ:37OP:T75C:YZXU:HCHV:YPI2
 Docker Root Dir: /home/newdisk/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

- OS: Ubuntu 20.04.2 LTS

**Comment by miguelaeh** [comment]
Hi @rightx2 ,
Are you using SeLinux?

**Comment by rightx2** [comment]
@miguelaeh no, Ubuntu

**Comment by javsalgar** [comment]
Hi,

Could it be that the mounted volumes do not have the proper permissions and therefore the Spark processes are unable to write ?

**Comment by rightx2** [comment]
@javsalgar You're right. I've solved this issue by `chmod -R 777 spark". Thanks!
