### ISSUE TITLE
spark-submit in cluster mode from host tries to use JAVA_HOME from host

### ISSUE THREAD

**Issue by mniehoff** [bitnami/bitnami-docker-spark#60]
**Description**

When running spark-submit with deploy-mode cluster from the host the spark application fails, as it is trying to use the JVM/JDK from the host which of course can not be found in the container.

**Steps to reproduce the issue:**

1. Adjust docker-compose.yml in this repository to allow access to port 7077
2. Run `spark-submit`:

```console
$ spark-submit --verbose --class org.apache.spark.examples.SparkPi --master spark://localhost:7077 --deploy-mode cluster file:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.1.2.jar
```

**Describe the results you received:**

The driver is submitted, but fails with the following error:

```console
21/12/06 16:44:09 INFO ClientEndpoint: State of driver-20211206154404-0000 is ERROR
21/12/06 16:44:09 ERROR ClientEndpoint: Exception from cluster was: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java" (in directory "/opt/bitnami/spark/work/driver-20211206154404-0000"): error=2, No such file or directory
java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java" (in directory "/opt/bitnami/spark/work/driver-20211206154404-0000"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.spark.deploy.worker.ProcessBuilderLike$$anon$3.start(DriverRunner.scala:275)
	at org.apache.spark.deploy.worker.DriverRunner.runCommandWithRetry(DriverRunner.scala:240)
	at org.apache.spark.deploy.worker.DriverRunner.runDriver(DriverRunner.scala:221)
	at org.apache.spark.deploy.worker.DriverRunner.prepareAndRunDriver(DriverRunner.scala:204)
	at org.apache.spark.deploy.worker.DriverRunner$$anon$2.run(DriverRunner.scala:99)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
```

**Describe the results you expected:**

I wonder if submitting applications from outside of the docker image is actually supported by this image. Or what must be made to support this feature? Currently I do not really understand where the host JAVA_HOME comes from. 

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:10 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 11
  Running: 4
  Paused: 0
  Stopped: 7
 Images: 15
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: H4Y3:RSTD:4ARU:CDOC:JQ6I:INVG:W6MP:NUHH:OYD2:IIEK:6LNX:3YWZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 84
  Goroutines: 92
  System Time: 2021-12-06T15:50:37.16561409Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Comment by mniehoff** [comment]
Hi Juan,

thanks for you response. Starting from another container is possible, yes.

Still imho there is still a problem with the interplay of host and container. Running the spark submit with a local standalone cluster works absolutely fine. Also the java exists at the path (/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java)

Also, this is the log of the worker when doing the spark submit and the driver is launched: 

```
spark_stand_alone-spark-worker-1  | 21/12/09 10:45:51 INFO Worker: Asked to launch driver driver-20211209104550-0000
spark_stand_alone-spark-worker-1  | 21/12/09 10:45:51 INFO DriverRunner: Copying user jar file:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.1.2.jar to /opt/bitnami/spark/work/driver-20211209104550-0000/spark-examples_2.12-3.1.2.jar
spark_stand_alone-spark-worker-1  | 21/12/09 10:45:51 INFO Utils: Copying /opt/bitnami/spark/examples/jars/spark-examples_2.12-3.1.2.jar to /opt/bitnami/spark/work/driver-20211209104550-0000/spark-examples_2.12-3.1.2.jar
spark_stand_alone-spark-worker-1  | 21/12/09 10:45:51 INFO DriverRunner: Launch Command: "/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java" "-cp" "/Users/matthiasniehoff/dev/tools/spark-3.1.2-bin-hadoop3.2/conf:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.supervise=false" "-Dspark.app.name=org.apache.spark.examples.SparkPi" "-Dspark.master=spark://localhost:7077" "-Dspark.submit.deployMode=cluster" "-Dspark.jars=file:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.1.2.jar" "-Dspark.submit.pyFiles=" "-Dspark.rpc.askTimeout=10s" "org.apache.spark.deploy.worker.DriverWrapper" "spark://Worker@172.18.0.2:45789" "/opt/bitnami/spark/work/driver-20211209104550-0000/spark-examples_2.12-3.1.2.jar" "org.apache.spark.examples.SparkPi"
spark_stand_alone-spark-worker-1  | 21/12/09 10:45:51 INFO DriverRunner: Killing driver process!
spark_stand_alone-spark-worker-1  | 21/12/09 10:45:51 WARN Worker: Driver driver-20211209104550-0000 failed with unrecoverable exception: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java" (in directory "/opt/bitnami/spark/work/driver-20211209104550-0000"): error=2, No such file or directory
```

So when the driver is started on the worker they are actually expecting Java in the path where it is on the host and completely ignoring the JAVA_HOME set in the container. I have no idea how this host path leaks into the container.

**Comment by rafariossaa** [comment]
Hi,
  It is not very clear to me if you have used what @juan131 indicated or not in your last try.
  Could you indicate that ?

**Comment by mniehoff** [comment]
No, this is still submitted from the host (in this case my laptop), not from within another docker container. when submitting from another bitnami-spark container instance it works just fine, as @juan131 suggested.

still, i am curious how this host specific paths (`/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java` `/Users/xxx/dev/tools/spark-3.1.2-bin-hadoop3.2/conf`) end up inside the docker container of the worker. Why is the worker looking for java in host specific path and does not recognize the JAVA_HOME set in the container? (see line 4 of the output in my second post)

The only explanation for me would be: the launch command for the driver in cluster mode is already built on the host when running the spark-submit script. then it would be a spark thing, nothing with the container. but this would also mean that it is not possible to run a spark driver in cluster mode on a standalone cluster when the filesystem structure of the host that executes spark-submit does not match the filesystem structure of the worker. this made me wonder if this maybe something within the containers.

hope this helps to understand the problem i am facing :-)

as said: submitting from another bitnami-spark container will be ok for me for my purposes. I was mainly curious if you have seen this problem before. If this isn't the case and for you it's "works as desinged", i am totally fine to close this isusse.

Thank you for your work!

**Comment by rafariossaa** [comment]
Hi,
  We don't develop using spark, I can not help you with those details on why the path get into the container. I would suggest you to ask in spark forums, maybe they can give you a proper answer as they know the insights of spark.
