### ISSUE TITLE
Spark master has dead

### ISSUE THREAD

**Issue by glcanvas** [bitnami/bitnami-docker-spark#62]
hi!
got error:
```spark_1           | 21/12/19 20:41:51 ERROR TransportRequestHandler: Error while invoking RpcHandler#receive() for one-way message.
spark_1           | java.io.InvalidClassException: org.apache.spark.deploy.ApplicationDescription; local class incompatible: stream classdesc serialVersionUID = 6543101073799644159, local class serialVersionUID = 1574364215946805297
spark_1           | 	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
spark_1           | 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2003)
spark_1           | 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
spark_1           | 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
spark_1           | 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
spark_1           | 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
spark_1           | 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
spark_1           | 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
spark_1           | 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
spark_1           | 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
spark_1           | 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
spark_1           | 	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
spark_1           | 	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:109)
spark_1           | 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$deserialize$2(NettyRpcEnv.scala:299)
spark_1           | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
spark_1           | 	at org.apache.spark.rpc.netty.NettyRpcEnv.deserialize(NettyRpcEnv.scala:352)
spark_1           | 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$deserialize$1(NettyRpcEnv.scala:298)
spark_1           | 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
spark_1           | 	at org.apache.spark.rpc.netty.NettyRpcEnv.deserialize(NettyRpcEnv.scala:298)
spark_1           | 	at org.apache.spark.rpc.netty.RequestMessage$.apply(NettyRpcEnv.scala:647)
spark_1           | 	at org.apache.spark.rpc.netty.NettyRpcHandler.internalReceive(NettyRpcEnv.scala:698)
spark_1           | 	at org.apache.spark.rpc.netty.NettyRpcHandler.receive(NettyRpcEnv.scala:690)
spark_1           | 	at org.apache.spark.network.server.TransportRequestHandler.processOneWayMessage(TransportRequestHandler.java:274)
spark_1           | 	at org.apache.spark.network.server.TransportRequestHandler.handle(TransportRequestHandler.java:111)
spark_1           | 	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:140)
spark_1           | 	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:53)
spark_1           | 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
spark_1           | 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
spark_1           | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
spark_1           | 	at org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:102)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
spark_1           | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
spark_1           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
spark_1           | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
spark_1           | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
spark_1           | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
spark_1           | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
spark_1           | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
spark_1           | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
spark_1           | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
spark_1           | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
spark_1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
spark_1           | 	at java.lang.Thread.run(Thread.java:748)
```
my docker compose file is:
``` 
 spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '18080:8080'
      - "7077:7077"
  spark-worker_1:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker_2:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no```

**Comment by javsalgar** [comment]
Hi,

Does this error appear directly when deploying? Or do you submit any job?
