### ISSUE TITLE
Cannot connect to the spark cluster

### ISSUE THREAD

**Issue by robertispas** [bitnami/bitnami-docker-spark#66]
**Description**

Hi,

I have setup a spark cluster using this image and I wanted to connect to it in order to perform some tasks using pySpark. However, I cannot seem to get any connection from either the container IP address, instance id (spark://f4729a3970ee:7077) or localhost.

Having a reliable cluster is part of my masters project so I am really keen to get this to work!

Maybe I misunderstood something about the setup, or one of my windows settings might affect it somehow?

**Steps to reproduce the issue:**

My `docker-compose.yml`:

```
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - ".:/test-files:rw"
  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

```

I then run `docker-compose up -d`, and attempt to connect to it as follows:

```
master = "spark://f4729a3970ee:7077"
conf = SparkConf().setAppName("framework").setMaster(master)
sc = SparkContext(conf=conf)
spark = SparkSession(sc)
```

After that I parralelize some tasks as usual, however the code never reaches that point because:

```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/01/29 21:00:12 WARN TransportClientFactory: DNS resolution failed for f4729a3970ee:7077 took 2291 ms
22/01/29 21:00:12 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master f4729a3970ee:7077
org.apache.spark.SparkException: Exception thrown in awaitResult:
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
        at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to connect to f4729a3970ee:7077
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
        at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
        ... 4 more
Caused by: java.net.UnknownHostException: f4729a3970ee
        at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at java.net.InetAddress.getByName(InetAddress.java:1077)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
```

**Describe the results you received:**

Essentially above.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

My current pySpark configuration runs on Python 3.8 and Spark 3.2 and Hadoop 3.2, with Java 8.

**Comment by robertispas** [comment]
I have manage to get the connection working! By using `spark://0.0.0.0:7077" seems to do the trick, however, I run into this issue now, on the worker:

```
Spark Executor Command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=65406" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@localhost:65406" "--executor-id" "0" "--hostname" "172.29.0.2" "--cores" "1" "--app-id" "app-20220129214640-0000" "--worker-url" "spark://Worker@172.29.0.2:40791"
========================================

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/01/29 21:46:41 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 141@7b4f7b8b25bd
22/01/29 21:46:41 INFO SignalUtils: Registering signal handler for TERM
22/01/29 21:46:41 INFO SignalUtils: Registering signal handler for HUP
22/01/29 21:46:41 INFO SignalUtils: Registering signal handler for INT
22/01/29 21:46:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/01/29 21:46:42 INFO SecurityManager: Changing view acls to: spark,Robert
22/01/29 21:46:42 INFO SecurityManager: Changing modify acls to: spark,Robert
22/01/29 21:46:42 INFO SecurityManager: Changing view acls groups to: 
22/01/29 21:46:42 INFO SecurityManager: Changing modify acls groups to: 
22/01/29 21:46:42 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark, Robert); groups with view permissions: Set(); users  with modify permissions: Set(spark, Robert); groups with modify permissions: Set()
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:419)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:408)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:439)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:437)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	... 4 more
Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:65406
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:65406
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by robertispas** [comment]
Hello again,

I have managed to get the connection working, however I am running into this issue now:

```
Spark Executor Command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=52761" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@host.docker.internal:52761" "--executor-id" "0" "--hostname" "172.30.0.2" "--cores" "1" "--app-id" "app-20220129221222-0000" "--worker-url" "spark://Worker@172.30.0.2:35763"
========================================

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/01/29 22:12:23 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 143@880dc1e85709
22/01/29 22:12:23 INFO SignalUtils: Registering signal handler for TERM
22/01/29 22:12:23 INFO SignalUtils: Registering signal handler for HUP
22/01/29 22:12:23 INFO SignalUtils: Registering signal handler for INT
22/01/29 22:12:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/01/29 22:12:23 INFO SecurityManager: Changing view acls to: spark,Robert
22/01/29 22:12:23 INFO SecurityManager: Changing modify acls to: spark,Robert
22/01/29 22:12:23 INFO SecurityManager: Changing view acls groups to: 
22/01/29 22:12:23 INFO SecurityManager: Changing modify acls groups to: 
22/01/29 22:12:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark, Robert); groups with view permissions: Set(); users  with modify permissions: Set(spark, Robert); groups with modify permissions: Set()
22/01/29 22:12:23 INFO TransportClientFactory: Successfully created connection to host.docker.internal/192.168.65.2:52761 after 53 ms (0 ms spent in bootstraps)
22/01/29 22:12:24 INFO SecurityManager: Changing view acls to: spark,Robert
22/01/29 22:12:24 INFO SecurityManager: Changing modify acls to: spark,Robert
22/01/29 22:12:24 INFO SecurityManager: Changing view acls groups to: 
22/01/29 22:12:24 INFO SecurityManager: Changing modify acls groups to: 
22/01/29 22:12:24 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark, Robert); groups with view permissions: Set(); users  with modify permissions: Set(spark, Robert); groups with modify permissions: Set()
22/01/29 22:12:24 INFO TransportClientFactory: Successfully created connection to host.docker.internal/192.168.65.2:52761 after 2 ms (0 ms spent in bootstraps)
22/01/29 22:12:24 INFO DiskBlockManager: Created local directory at /tmp/spark-e10917b3-6e69-4786-aae5-ef7d351b9540/executor-ccd2f625-0ff3-49c4-989a-599b1d5666a5/blockmgr-7d308435-f655-4c64-8d74-b87c44da2f6e
22/01/29 22:12:24 INFO MemoryStore: MemoryStore started with capacity 366.3 MiB
22/01/29 22:12:24 INFO CoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@host.docker.internal:52761
22/01/29 22:12:24 INFO WorkerWatcher: Connecting to worker spark://Worker@172.30.0.2:35763
22/01/29 22:12:24 INFO TransportClientFactory: Successfully created connection to /172.30.0.2:35763 after 1 ms (0 ms spent in bootstraps)
22/01/29 22:12:24 INFO WorkerWatcher: Successfully connected to spark://Worker@172.30.0.2:35763
22/01/29 22:12:24 INFO ResourceUtils: ==============================================================
22/01/29 22:12:24 INFO ResourceUtils: No custom resources configured for spark.executor.
22/01/29 22:12:24 INFO ResourceUtils: ==============================================================
22/01/29 22:12:24 INFO CoarseGrainedExecutorBackend: Successfully registered with driver
22/01/29 22:12:24 INFO Executor: Starting executor ID 0 on host 172.30.0.2
22/01/29 22:12:24 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45807.
22/01/29 22:12:24 INFO NettyBlockTransferService: Server created on 172.30.0.2:45807
22/01/29 22:12:24 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
22/01/29 22:12:24 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(0, 172.30.0.2, 45807, None)
22/01/29 22:12:24 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(0, 172.30.0.2, 45807, None)
22/01/29 22:12:24 INFO BlockManager: Initialized BlockManager: BlockManagerId(0, 172.30.0.2, 45807, None)
22/01/29 22:12:24 INFO CoarseGrainedExecutorBackend: Got assigned task 0
22/01/29 22:12:24 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
22/01/29 22:12:24 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.io.InvalidClassException: org.apache.spark.util.AccumulatorV2; local class incompatible: stream classdesc serialVersionUID = 8273715124741334009, local class serialVersionUID = 574976528730727648
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:109)
	at org.apache.spark.scheduler.Task.metrics$lzycompute(Task.scala:72)
	at org.apache.spark.scheduler.Task.metrics(Task.scala:71)
	at org.apache.spark.scheduler.Task.run(Task.scala:100)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
22/01/29 22:12:24 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker for task 0.0 in stage 0.0 (TID 0),5,main]
java.lang.Error: java.io.InvalidClassException: org.apache.spark.util.AccumulatorV2; local class incompatible: stream classdesc serialVersionUID = 8273715124741334009, local class serialVersionUID = 574976528730727648
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.InvalidClassException: org.apache.spark.util.AccumulatorV2; local class incompatible: stream classdesc serialVersionUID = 8273715124741334009, local class serialVersionUID = 574976528730727648
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:109)
	at org.apache.spark.scheduler.Task.metrics$lzycompute(Task.scala:72)
	at org.apache.spark.scheduler.Task.metrics(Task.scala:71)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$collectAccumulatorsAndResetStatusOnFailure$1(Executor.scala:424)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$collectAccumulatorsAndResetStatusOnFailure$1$adapted(Executor.scala:423)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.executor.Executor$TaskRunner.collectAccumulatorsAndResetStatusOnFailure(Executor.scala:423)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:704)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	... 2 more
22/01/29 22:12:24 INFO MemoryStore: MemoryStore cleared
22/01/29 22:12:24 INFO BlockManager: BlockManager stopped
22/01/29 22:12:24 INFO ShutdownHookManager: Shutdown hook called
```

**Comment by robertispas** [comment]
This has been resolved! A Spark version mismatch was the cause.
