### ISSUE TITLE
Cannot install third party python packages

### ISSUE THREAD

**Issue by robertispas** [bitnami/bitnami-docker-spark#67]
**Description**

Hi,

I have been trying to install the package requests on the master container, as it is required for me program. Unfortunately, I come across this issue:

```
(venv) root@d374e1f453f4:/opt/bitnami/spark/venv/lib/python3.8/site-packages# pip install requests
Traceback (most recent call last):
  File "/opt/bitnami/spark/venv/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_internal/configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 8, in <module>
    from pip._vendor.requests.models import Request, Response
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 135, in <module>
    from . import utils
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 41, in <module>
    DEFAULT_CA_BUNDLE_PATH = certs.where()
  File "/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 51, in where
    _CACERT_PATH = str(_CACERT_CTX.__enter__())
  File "/opt/bitnami/python/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/bitnami/python/lib/python3.8/importlib/resources.py", line 203, in path
    with open_binary(package, resource) as fp:
  File "/opt/bitnami/python/lib/python3.8/importlib/resources.py", line 91, in open_binary
    return reader.open_resource(resource)
  File "<frozen importlib._bootstrap_external>", line 1048, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/spark/venv/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem'

```

**Steps to reproduce the issue:**

1. The docker-compose file:

```
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ".:/opt/bitnami/test-files:rw"
    networks:
      - spark
  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_WORKER_MEMORY=4G
    ports:
      - '8081:8081'
    volumes:
      - ".:/opt/bitnami/test-files:rw"
    networks:
      - spark

networks:
  spark:
    driver: bridge
```

2. `docker-compose up -d`
3. `docker ps`
4. `docker exec -it --user root [master container id] bash`
5. Activate the virtual environment in venv.
6. Run `pip install requests`

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

The file missing is related to another package which I can't see installed, so I'm guessing it isn't?

**Comment by juan131** [comment]
Hi @robertispas 

We highly discourage to install new Python packages at runtime. Instead, you should extend the Bitnami Spark image to include your custom packages or jars so the image you used already contains everything you need to run your Spark application. Find more information in the link below:

- https://github.com/bitnami/bitnami-docker-spark#installing-additional-jars

**Comment by robertispas** [comment]
Hey @juan131,

Thank you for the response! I used something similar to this and ran into the same issue of libraries missing:

```
FROM docker.io/bitnami/spark:3

USER root

ADD requirements.txt /opt/bitnami/spark
RUN pip install --user -r requirements.txt
```

Do I have to specifically activate the virtual environment before running pip?

Cheers!

**Comment by juan131** [comment]
Yes @robertispas 

You need to do sth like this:

```bash
. /opt/bitnami/airflow/venv/bin/activate
pip install -r requirements.txt
deactivate
```

**Comment by robertispas** [comment]
Hey @juan131,

Thank you so much for the help! I finally managed to get it to work with the following Dockerfile. I'll leave it below in case someone ever has a similar problem!

```
FROM docker.io/bitnami/spark:3

USER root

ENV VIRTUAL_ENV=/opt/bitnami/airflow/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ADD requirements.txt /opt/bitnami/spark
RUN pip install -r requirements.txt
```

Thank you for the help, and for this awesome image!

Robert
