### ISSUE TITLE
Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found

### ISSUE THREAD

**Issue by augcollet** [bitnami/bitnami-docker-spark#72]
Hello,

I'm trying to read a CSV file on Azure Blob Storage with pyspark from a Jupyter Notebook, but I'm facing the following error:

```
Py4JJavaError: An error occurred while calling o34.csv.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:747)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:745)
	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:577)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:571)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2571)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2665)
	... 29 more
```

Here are the steps I followed:

- I have a kubernetes cluster available
- I installed a HELM chart JupyterHub which seems to work correctly, I installed Pyspark there
- I installed a HELM Chart (Bitnami) to set up a Spark cluster
- I was able to connect to my Spark cluster via pyspark from a Jupyter notebook

![image](https://user-images.githubusercontent.com/99130480/152686280-0bdbc9b5-a87c-472b-97ad-5db19848f003.png)

- I can execute some commands in remote Spark without any issue :

![image](https://user-images.githubusercontent.com/99130480/152686356-b5a783dd-75dc-4395-81c1-d2d4cd08b5ec.png)

- I tried to read a csv file located on a Blob Storage, but I get the error message that I pasted above

![image](https://user-images.githubusercontent.com/99130480/152686381-d426e97e-3be2-4955-a1c8-d9e77529b35d.png)

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
```

- After some research, I saw that it was necessary to install multiple jars (at least hadoop-azure and azure-storage), so I did it in a Dockerfile, as mentionned in Bitnami Documentation :

![image](https://user-images.githubusercontent.com/99130480/152686523-6ee98b59-588d-4ce6-aca8-228bd3d7de03.png)

![image](https://user-images.githubusercontent.com/99130480/152686834-247080a5-a86a-4ed1-89df-08d7c4a53b86.png)

- I redeployed my Spark cluster, the jars are present in the expected folder:

![image](https://user-images.githubusercontent.com/99130480/152686482-b1bbc75d-93d5-4565-ad55-bda374226ac1.png)

However, I still get the same error:

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
```

I have tried a lot of configurations found on stackoverflow but still get the same result.

![image](https://user-images.githubusercontent.com/99130480/152686642-57310a00-c51a-44d4-a7b0-23ec598db15f.png)
![image](https://user-images.githubusercontent.com/99130480/152686650-64a86a77-d929-4517-b86a-c99cfd0896a8.png)
![image](https://user-images.githubusercontent.com/99130480/152686667-322eedf5-03ef-4af6-acda-f4f176566791.png)

No matter what configuration I try, when I try to read the CSV file I get the same error message.

I don't really know what to try anymore, there are certainly things that escape me.

I hope someone here can help me?

**Comment by carrodher** [comment]
Thanks for creating the ticket, it seems a really complex scenario difficult to reproduce on our side. For information regarding the application itself or customization of the content within the application; we highly recommend checking forums and user guides made available by the project behind the application.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by augcollet** [comment]
Hello,

Thanks for your feedback.

I'm still stuck with the same error message, but I think I've made some progress.

Here is my current command:
```
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark import SparkConf, SparkContext

conf = SparkConf()
conf.setMaster('spark://spark-master-svc.default.svc.cluster.local:7077')
conf.setAppName('spark-basic')
conf.set("spark.driver.host", "jupyter-headless.default.svc.cluster.local")
conf.set('spark.driver.port', '40694')
conf.set('spark.submit.deployMode', 'client')

conf.set("fs.azure.account.auth.type", "SharedKey")
conf.set(
"fs.azure.account.key.***.blob.core.windows.net",
"***"
)

conf.set("spark.hadoop.fs.wasb.impl", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
conf.set("fs.azure", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
conf.set("fs.wasb.impl", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")

conf.set("spark.jars", "local:///opt/bitnami/spark/jars/hadoop-azure-3.3.1.jar,local:///opt/bitnami/spark/jars/azure-storage-8.6.6.jar")
## My jars are in folder /opt/bitnami/spark/jars/ in all spark nodes (via Dockerfile)

spark = SparkSession.builder.config(conf=conf).getOrCreate()
sc=spark.sparkContext
sc
```

Output : 
![image](https://user-images.githubusercontent.com/99130480/153208851-d17ec8ac-3279-4d8d-af4a-dc50f72bf10a.png)

Now I am sure that my jars are well recognized and imported into my session:
![image](https://user-images.githubusercontent.com/99130480/153208889-d30a77d2-5a90-4bc3-8122-84cf07f68e91.png)
(worker logs :)
![image](https://user-images.githubusercontent.com/99130480/153208960-a54442d0-1d31-443b-94f5-cdd8adb3e5f3.png)

However, I still get the same error:
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [3], in <module>
      1 file_path = "wasb://travaux@ineoxinvivo.blob.core.windows.net/Quentin_REMPLAKOWSKI/20220130_ACTIONQUEUE.csv"
      3 print(file_path)
----> 5 df_csv = spark.read.csv(
      6     path=file_path,
      7     sep='|',
      8     inferSchema=True,
      9     header=True
     10 )
     11 df_csv

File /opt/conda/lib/python3.9/site-packages/pyspark/sql/readwriter.py:410, in DataFrameReader.csv(self, path, schema, sep, encoding, quote, escape, comment, header, inferSchema, ignoreLeadingWhiteSpace, ignoreTrailingWhiteSpace, nullValue, nanValue, positiveInf, negativeInf, dateFormat, timestampFormat, maxColumns, maxCharsPerColumn, maxMalformedLogPerPartition, mode, columnNameOfCorruptRecord, multiLine, charToEscapeQuoteEscaping, samplingRatio, enforceSchema, emptyValue, locale, lineSep, pathGlobFilter, recursiveFileLookup, modifiedBefore, modifiedAfter, unescapedQuoteHandling)
    408     path = [path]
    409 if type(path) == list:
--> 410     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    411 elif isinstance(path, RDD):
    412     def func(iterator):

File /opt/conda/lib/python3.9/site-packages/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /opt/conda/lib/python3.9/site-packages/pyspark/sql/utils.py:111, in capture_sql_exception.<locals>.deco(*a, **kw)
    109 def deco(*a, **kw):
    110     try:
--> 111         return f(*a, **kw)
    112     except py4j.protocol.Py4JJavaError as e:
    113         converted = convert_exception(e.java_exception)

File /opt/conda/lib/python3.9/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o74.csv.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:747)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:745)
	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:577)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:571)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2571)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2665)
	... 29 more
```

Maybe with this new information someone could help me?
