### ISSUE TITLE
How to use GraphFrames with the bitnami spark docker container

### ISSUE THREAD

**Issue by scign** [bitnami/bitnami-docker-spark#74]
### Name and Version

bitnami/spark:3.2.1

### What steps will reproduce the bug?

OS: Windows 10
Jupyter notebook, python virtual environment running python 3.8.10, running on the docker host.

## Tested fine without GraphFrames:
Downloaded the YML file from [here](https://github.com/bitnami/bitnami-docker-spark/blob/master/docker-compose.yml) today and ran `docker-compose up` after exposing port 7077 on the master.
The following successfully created a context and session and I was able to use the session to run a simple pi calculator from [this link](https://www.sicara.ai/blog/2017-05-02-get-started-pyspark-jupyter-notebook-3-minutes) and a simple dataframe example adapted from [this other issue](https://github.com/bitnami/bitnami-docker-spark/issues/18)
```
import os
import pandas as pd
from pyspark import SparkContext
from pyspark.sql import SparkSession
from graphframes import GraphFrame

sc = SparkContext(master='spark://localhost:7077', appName='myApp')
spark_sess = SparkSession.builder \
    .config(conf=sc.getConf())
    .getOrCreate()
```

## Issue
Did the following to try and add graphframes:
Downloaded [graphframes 0.8.2-spark3.2-s_2.12](https://spark-packages.org/package/graphframes/graphframes) and placed it in C:\Temp\graphframes-0.8.2-spark3.2-s_2.12.jar

Updated docker-compose.yml:
```
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - type: bind
        source: c/Temp/graphframes-0.8.2-spark3.2-s_2.12.jar
        target: /opt/bitnami/spark/jars/graphframes-0.8.2-spark3.2-s_2.12.jar

  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: c/Temp/graphframes-0.8.2-spark3.2-s_2.12.jar
        target: /opt/bitnami/spark/jars/graphframes-0.8.2-spark3.2-s_2.12.jar
```

Ran `docker-compose up` and confirmed that the master and worker both started successfully.
Docker console output:
```
C:\Users\path-to-my-project>docker-compose up
[+] Running 2/2
 - Container pyspark-link-prediction-spark-worker-1  Created                                                                                                                                       0.0s
 - Container pyspark-link-prediction-spark-1         Recreated                                                                                                                                     0.8s
Attaching to pyspark-link-prediction-spark-1, pyspark-link-prediction-spark-worker-1
pyspark-link-prediction-spark-worker-1  |  23:11:32.77
pyspark-link-prediction-spark-worker-1  |  23:11:32.77 Welcome to the Bitnami spark container
pyspark-link-prediction-spark-worker-1  |  23:11:32.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
pyspark-link-prediction-spark-worker-1  |  23:11:32.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
pyspark-link-prediction-spark-worker-1  |  23:11:32.78
pyspark-link-prediction-spark-worker-1  |  23:11:32.78 INFO  ==> ** Starting Spark setup **
pyspark-link-prediction-spark-worker-1  |  23:11:32.79 INFO  ==> Detected mounted configuration file...
pyspark-link-prediction-spark-worker-1  |  23:11:32.79 INFO  ==> ** Spark setup finished! **
pyspark-link-prediction-spark-worker-1  |
pyspark-link-prediction-spark-worker-1  |  23:11:32.81 INFO  ==> ** Starting Spark in worker mode **
pyspark-link-prediction-spark-worker-1  | starting org.apache.spark.deploy.worker.Worker, logging to /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.worker.Worker-1-8504994de50e.out
pyspark-link-prediction-spark-1         |  23:11:32.94
pyspark-link-prediction-spark-1         |  23:11:32.94 Welcome to the Bitnami spark container
pyspark-link-prediction-spark-1         |  23:11:32.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
pyspark-link-prediction-spark-1         |  23:11:32.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
pyspark-link-prediction-spark-1         |  23:11:32.95
pyspark-link-prediction-spark-1         |  23:11:32.95 INFO  ==> ** Starting Spark setup **
pyspark-link-prediction-spark-1         |  23:11:32.96 INFO  ==> Generating Spark configuration file...
pyspark-link-prediction-spark-1         |  23:11:32.97 INFO  ==> ** Spark setup finished! **
pyspark-link-prediction-spark-1         |
pyspark-link-prediction-spark-worker-1  | Spark Command: /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark:7077
pyspark-link-prediction-spark-worker-1  | ========================================
pyspark-link-prediction-spark-1         |  23:11:32.98 INFO  ==> ** Starting Spark in master mode **
pyspark-link-prediction-spark-1         | starting org.apache.spark.deploy.master.Master, logging to /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.master.Master-1-88fbc65b5ce5.out
pyspark-link-prediction-spark-1         | Spark Command: /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org.apache.spark.deploy.master.Master --host 88fbc65b5ce5 --port 7077 --webui-port 8080
pyspark-link-prediction-spark-1         | ========================================
pyspark-link-prediction-spark-worker-1  | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO Worker: Started daemon with process name: 37@8504994de50e
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SignalUtils: Registering signal handler for TERM
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SignalUtils: Registering signal handler for HUP
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SignalUtils: Registering signal handler for INT
pyspark-link-prediction-spark-1         | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO Master: Started daemon with process name: 39@88fbc65b5ce5
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SignalUtils: Registering signal handler for TERM
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SignalUtils: Registering signal handler for HUP
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SignalUtils: Registering signal handler for INT
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SecurityManager: Changing view acls to: spark
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SecurityManager: Changing modify acls to: spark
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SecurityManager: Changing view acls groups to:
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SecurityManager: Changing modify acls groups to:
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:33 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SecurityManager: Changing view acls to: spark
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SecurityManager: Changing modify acls to: spark
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SecurityManager: Changing view acls groups to:
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SecurityManager: Changing modify acls groups to:
pyspark-link-prediction-spark-1         | 22/03/20 23:11:33 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO Utils: Successfully started service 'sparkWorker' on port 43871.
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO Worker: Worker decommissioning not enabled.
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO Worker: Starting Spark worker 172.18.0.2:43871 with 2 cores, 1024.0 MiB RAM
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO Worker: Running Spark version 3.2.1
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO Worker: Spark home: /opt/bitnami/spark
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO ResourceUtils: ==============================================================
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO ResourceUtils: No custom resources configured for spark.worker.
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO ResourceUtils: ==============================================================
pyspark-link-prediction-spark-1         | 22/03/20 23:11:34 INFO Utils: Successfully started service 'sparkMaster' on port 7077.
pyspark-link-prediction-spark-1         | 22/03/20 23:11:34 INFO Master: Starting Spark master at spark://88fbc65b5ce5:7077
pyspark-link-prediction-spark-1         | 22/03/20 23:11:34 INFO Master: Running Spark version 3.2.1
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO WorkerWebUI: Bound WorkerWebUI to 0.0.0.0, and started at http://8504994de50e:8081
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO Worker: Connecting to master spark:7077...
pyspark-link-prediction-spark-1         | 22/03/20 23:11:34 INFO Utils: Successfully started service 'MasterUI' on port 8080.
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:34 INFO TransportClientFactory: Successfully created connection to spark/172.18.0.3:7077 after 22 ms (0 ms spent in bootstraps)
pyspark-link-prediction-spark-1         | 22/03/20 23:11:34 INFO MasterWebUI: Bound MasterWebUI to 0.0.0.0, and started at http://88fbc65b5ce5:8080
pyspark-link-prediction-spark-1         | 22/03/20 23:11:34 INFO Master: Registering worker 172.18.0.2:43871 with 2 cores, 1024.0 MiB RAM
pyspark-link-prediction-spark-1         | 22/03/20 23:11:34 INFO Master: I have been elected leader! New state: ALIVE
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:45 INFO Worker: Retrying connection to master (attempt # 1)
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:45 INFO Worker: Connecting to master spark:7077...
pyspark-link-prediction-spark-1         | 22/03/20 23:11:45 INFO Master: Registering worker 172.18.0.2:43871 with 2 cores, 1024.0 MiB RAM
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:11:45 INFO Worker: Successfully registered with master spark://88fbc65b5ce5:7077
```

Status on localhost showed:
```
URL: spark://76b5080ff4c3:7077
Alive Workers: 1
Cores in use: 2 Total, 0 Used
Memory in use: 1024.0 MiB Total, 0.0 B Used
Resources in use:
Applications: 0 Running, 0 Completed
Drivers: 0 Running, 0 Completed
Status: ALIVE
```

Ran the following in a Jupyter notebook:
```
import os
import pandas as pd
from pyspark import SparkContext
from pyspark.sql import SparkSession
from graphframes import GraphFrame

sc = SparkContext(master='spark://localhost:7077', appName='myApp')
spark_sess = SparkSession.builder \
    .config(conf=sc.getConf()) \
    .config('spark.jars', '/opt/bitnami/spark/jars') \
    .config('spark.jars.ivy', '/opt/bitnami/spark/ivy') \
    .config('spark.jars.packages', 'graphframes:graphframes-0.8.2-spark3.2-s_2.12') \
    .getOrCreate()
```
```
df_nodes = pd.DataFrame([
    ['A'],['B'],['C'],['D']
], columns=['id'])

df_rels = pd.DataFrame([
    ('A','B'),
    ('B','C'),
    ('C','D')
], columns=['src','dst'])
```
```
gf = GraphFrame(
    spark_sess.createDataFrame(df_nodes),
    spark_sess.createDataFrame(df_rels)
)
```

### What is the expected behavior?

No output in the Jupyter notebook

### What do you see instead?

No output for the first 2 cells (expected)
Third cell (instantiating the GraphFrame) gives the following error.
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 gf = GraphFrame(
      2     spark_sess.createDataFrame(df_nodes),
      3     spark_sess.createDataFrame(df_rels)
      4 )

File C:\Venvs\pyspark38\lib\site-packages\graphframes\graphframe.py:65, in GraphFrame.__init__(self, v, e)
     63 self._sqlContext = v.sql_ctx
     64 self._sc = self._sqlContext._sc
---> 65 self._jvm_gf_api = _java_api(self._sc)
     67 self.ID = self._jvm_gf_api.ID()
     68 self.SRC = self._jvm_gf_api.SRC()

File C:\Venvs\pyspark38\lib\site-packages\graphframes\graphframe.py:38, in _java_api(jsc)
     36 def _java_api(jsc):
     37     javaClassName = "org.graphframes.GraphFramePythonAPI"
---> 38     return jsc._jvm.Thread.currentThread().getContextClassLoader().loadClass(javaClassName) \
     39             .newInstance()

File C:\Venvs\pyspark38\lib\site-packages\py4j\java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File C:\Venvs\pyspark38\lib\site-packages\pyspark\sql\utils.py:111, in capture_sql_exception.<locals>.deco(*a, **kw)
    109 def deco(*a, **kw):
    110     try:
--> 111         return f(*a, **kw)
    112     except py4j.protocol.Py4JJavaError as e:
    113         converted = convert_exception(e.java_exception)

File C:\Venvs\pyspark38\lib\site-packages\py4j\protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o147.loadClass.
: java.lang.ClassNotFoundException: org.graphframes.GraphFramePythonAPI
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Unknown Source)
```

### Additional information

I suspect that the issue is with the docker-compose.yml file and I haven't constructed it properly so that the graphframes jar is accessible. I probably also have an error in how I initialize the spark session from the context.

The following also appears in the docker console output when the context and session are created, which I presume is expected:
```
pyspark-link-prediction-spark-1         | 22/03/20 23:12:00 INFO Master: Registering app myApp
pyspark-link-prediction-spark-1         | 22/03/20 23:12:00 INFO Master: Registered app myApp with ID app-20220320231200-0000
pyspark-link-prediction-spark-1         | 22/03/20 23:12:00 INFO Master: Launching executor app-20220320231200-0000/0 on worker worker-20220320231134-172.18.0.2-43871
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:12:00 INFO Worker: Asked to launch executor app-20220320231200-0000/0 for myApp
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:12:00 INFO SecurityManager: Changing view acls to: spark
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:12:00 INFO SecurityManager: Changing modify acls to: spark
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:12:00 INFO SecurityManager: Changing view acls groups to:
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:12:00 INFO SecurityManager: Changing modify acls groups to:
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:12:00 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
pyspark-link-prediction-spark-worker-1  | 22/03/20 23:12:00 INFO ExecutorRunner: Launch command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=8795" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@acer-nitro.mshome.net:8795" "--executor-id" "0" "--hostname" "172.18.0.2" "--cores" "2" "--app-id" "app-20220320231200-0000" "--worker-url" "spark://Worker@172.18.0.2:43871"
```

**Comment by javsalgar** [comment]
Hi,

Could you enter the spark container and check if the jar file is located in the expected `/opt/bitnami/spark/jars` folder? 

https://github.com/bitnami/bitnami-docker-spark#installing-additional-jars
