### ISSUE TITLE
Custom spark images with Python 3.9.*?

### ISSUE THREAD

**Issue by porscheme** [bitnami/bitnami-docker-spark#78]
### Name and Version

bitnami/spark:3

### What is the problem this feature will solve?

- Need to instructions to make custom Spark container images with python version 3.9.*
- Want to make call K8S Spark cluster from notebook using Pyspark and Python version 3.9.*
- The bitnami/spark:3 container image uses 3.8.*
- We currently blocked by bellow error
```
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 481, in main
    raise RuntimeError(("Python in worker has different version %s than that in " +
RuntimeError: Python in worker has different version 3.8 than that in driver 3.9, PySpark cannot run with different minor versions. Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:555)
```

### What is the feature you are proposing to solve the problem?

- None

### What alternatives have you considered?

- None

**Comment by javsalgar** [comment]
Hi,

You may need to build a custom container using the Dockerfile:

https://github.com/bitnami/bitnami-docker-spark/blob/master/3/debian-10/Dockerfile

In the section where it installs python, change the version. You can see this one as an example:

https://github.com/bitnami/bitnami-docker-python/blob/master/3.9/debian-10/Dockerfile

In the future we may change the python version in the containers, but we cannot guarantee an ETA.

**Comment by porscheme** [comment]
@javsalgar thanks for the reply
- I was able to workaround the issue by making a custom images as you also suggested
- Also, copied few additional jar files, hadoop-azure-2.8.5.jar and azure-storage-8.6.4.jar including dependencies (not sure if required though)
- I'm getting below error when trying to read parquet files from Azure Storage account. Someone also reported similar issue on stackoverflow [link](https://stackoverflow.com/questions/71008716/pyspark-azure-blob-storage-class-org-apache-hadoop-fs-azure-nativeazurefilesys)
```
Py4JJavaError: An error occurred while calling o39.parquet.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.NativeAzureFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:747)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:745)
	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:577)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:596)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by porscheme** [comment]
I'm getting 'Java gateway process exited before sending its port number' error when I added 

this line of to my pySpark notebook
```
conf.set('spark.driver.host', socket.gethostbyname(socket.gethostname()))
```

### Below is my complete notebook
```
conf = SparkConf()
conf.setMaster("spark://spark-cluster-master-svc.cohort-workbench.svc.cluster.local:7077")
conf.setAppName("MyApp")
conf.set('spark.driver.host', socket.gethostbyname(socket.gethostname()))
conf.set('spark.submit.deployMode', 'client')
conf.set("spark.jars.packages", "org.apache.hadoop:hadoop-azure-3.3.1,com.microsoft.azure:azure-storage:8.6.6")
conf.set('spark.executor.instances', '2')
spark = SparkSession.builder.config(conf=conf).getOrCreate()

sc = spark.sparkContext

hd_conf = sc._jsc.hadoopConfiguration()
hd_conf.set("fs.azure.sas." + storage_container + "." + storage_account_name + ".blob.core.windows.net", storage_sas_token)
hd_conf.set("fs.azure","org.apache.hadoop.fs.azure.NativeAzureFileSystem")
hd_conf.set("spark.hadoop.fs.wasbs.impl","org.apache.hadoop.fs.azure.NativeAzureFileSystem")
hd_conf.set("fs.AbstractFileSystem.wasbs.impl", "org.apache.hadoop.fs.azure.Wasbs")
hd_conf.set("fs.wasbs.impl", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
hd_conf.set("spark.hadoop.fs.adl.impl", "org.apache.hadoop.fs.adl.AdlFileSystem")
    
parquet_file = "wasbs://documents@stdevtrvphiwus2.blob.core.windows.net/test/Truveta.Doc/document/1af35c98-25ab-583b-b65b-8677cfe7dfa7/1.0/PatientDocument/2022_1_16_19/part-00000-tid-3955423952229111404-e8a03cbf-7ec0-4916-8ac1-8fe9970f3253-3175-1-c000.snappy.parquet"
df = spark.read.parquet(parquet_file)
sc.stop()
```

**Comment by javsalgar** [comment]
Hi,

As mentioned here: https://github.com/bitnami/charts/issues/9806#issuecomment-1101208481, I don't think we can provide support to this level of customization. I would ask the plugin devs for more insight on this issue. Anyways, I will leave the the ticket open in case someone from the community has experience with this.
