### ISSUE TITLE
Cannot add additional JAR files (hadoop-azure-3.3.1.jar, azure-storage-8.6.6.jar) to custom container image

### ISSUE THREAD

**Issue by porscheme** [bitnami/bitnami-docker-spark#79]
### Name and Version

bitnami/spark:3

### What steps will reproduce the bug?

1. Create custom spark container image with additional JAR files
2. Attached docker file has hadoop-azure-3.3.1.jar, azure-storage-8.6.6.jar, and dependencies
[Dockerfile.spark.txt](https://github.com/bitnami/bitnami-docker-spark/files/8492798/Dockerfile.spark.txt)

3. Run produced custom docker image using command similar to below
```
docker run --rm -it <custom_image_from_above_step>
```
![Screenshot 2022-04-14 162133 PNG](https://user-images.githubusercontent.com/29828396/163492554-fbd41ee5-4738-4ca1-8eac-eab7abf0f263.jpg)

4. Open another terminal and connect to the running docker container in step 3 bash
5. Run below command 
```
pyspark --packages org.apache.hadoop:hadoop-azure:3.3.1,com.microsoft.azure:azure-storage:8.6.6
```

### What is the expected behavior?

packages must loaded

### What do you see instead?

:hadoop-azure:3.3.1,com.microsoft.azure:azure-storage:8.6.6
Python 3.8.13 (default, Apr 11 2022, 12:27:15)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
:: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
org.apache.hadoop#hadoop-azure added as a dependency
com.microsoft.azure#azure-storage added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-0aaec6b9-5d40-4793-b19d-35af6d4d7168;1.0
        confs: [default]
Exception in thread "main" java.io.FileNotFoundException: /opt/bitnami/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-0aaec6b9-5d40-4793-b19d-35af6d4d7168-1.0.xml (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:71)
        at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:63)
        at org.apache.ivy.core.module.descriptor.DefaultModuleDescriptor.toIvyFile(DefaultModuleDescriptor.java:553)
        at org.apache.ivy.core.cache.DefaultResolutionCacheManager.saveResolvedModuleDescriptor(DefaultResolutionCacheManager.java:183)
        at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:259)
        at org.apache.ivy.Ivy.resolve(Ivy.java:522)
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1445)
        at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:898)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Traceback (most recent call last):
  File "/opt/bitnami/spark/python/pyspark/shell.py", line 35, in <module>
    SparkContext._ensure_initialized()  # type: ignore
  File "/opt/bitnami/spark/python/pyspark/context.py", line 339, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/opt/bitnami/spark/python/pyspark/java_gateway.py", line 108, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
>>>

### Additional information

![Screenshot 2022-04-14 162133 PNG](https://user-images.githubusercontent.com/29828396/163493639-51bdfb77-578e-4cd3-93c7-0fa40ad94ee7.jpg)

**Comment by porscheme** [comment]
Is this because this [issue](https://stackoverflow.com/questions/60630832/i-cannot-use-package-option-on-bitnami-spark-docker-container)

**Comment by OneCricketeer** [comment]
FWIW, rather than all those curl commands, you could use `mvn dependency:get`

**Comment by porscheme** [comment]
> Hello @porscheme,
> 
> As you said, your error could be related to the permissions configuration this container uses. I tested downloading the jars in a local directory which I mounted in the container and the command you provided run successfully. You will need to create the local directory where the jars will be downloaded as explained in [#7 (comment)](https://github.com/bitnami/bitnami-docker-spark/issues/7#issuecomment-650968888)
> 
> The files and the docker-compose configuration I used were the following:
> 
> ```
> $ ls -la
> total 8
> drwxr-xr-x  5 fdepaz  160 Apr 18 17:18 .
> drwxr-xr-x 50 fdepaz 1600 Apr 18 16:24 ..
> -rw-r--r--  1 fdepaz  918 Apr 18 17:12 docker-compose.yml
> drwxrwxrwx 27 fdepaz  864 Apr 18 17:14 jars_dir
> -rw-r--r--  1 fdepaz   43 Apr 18 16:40 spark-defaults.conf
> 
> $ ls jars_dir
> animal-sniffer-annotations-1.14.jar  checker-compat-qual-2.0.0.jar	guava-24.1.1-jre.jar	       j2objc-annotations-1.1.jar     jetty-util-9.4.40.v20210413.jar
> aws-java-sdk-bundle-1.11.704.jar     commons-codec-1.11.jar		hadoop-azure-3.3.1.jar	       jackson-core-2.9.4.jar	      jetty-util-ajax-9.4.40.v20210413.jar
> azure-keyvault-core-1.2.4.jar	     commons-lang3-3.4.jar		hadoop-shaded-guava-1.1.1.jar  jackson-core-asl-1.9.13.jar    jsr305-1.3.9.jar
> azure-storage-8.6.6.jar		     commons-logging-1.1.3.jar		httpclient-4.5.13.jar	       jackson-mapper-asl-1.9.13.jar  slf4j-api-1.7.12.jar
> cache				     error_prone_annotations-2.1.3.jar	httpcore-4.4.13.jar	       jars			      wildfly-openssl-1.0.7.Final.jar
> 
> $ cat spark-defaults.conf
> spark.jars.ivy /opt/bitnami/spark/jars/ivy
> 
> $ cat docker-compose.yml
> version: '2'
> 
> services:
>   spark:
>     image: bitnami/spark
>     environment:
>       - SPARK_MODE=master
>       - SPARK_RPC_AUTHENTICATION_ENABLED=no
>       - SPARK_RPC_ENCRYPTION_ENABLED=no
>       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
>       - SPARK_SSL_ENABLED=no
>     ports:
>       - '8080:8080'
>     volumes:
>       - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
>       - ./jars_dir:/opt/bitnami/spark/jars/ivy:z
>   spark-worker:
>     image: bitnami/spark
>     environment:
>       - SPARK_MODE=worker
>       - SPARK_MASTER_URL=spark://spark:7077
>       - SPARK_WORKER_MEMORY=1G
>       - SPARK_WORKER_CORES=1
>       - SPARK_RPC_AUTHENTICATION_ENABLED=no
>       - SPARK_RPC_ENCRYPTION_ENABLED=no
>       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
>       - SPARK_SSL_ENABLED=no
>     volumes:
>       - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
>       - ./jars_dir:/opt/bitnami/spark/jars/ivy:z
> ```
> 
> You are getting issues because user 1001 doesn't have write permissions in `opt/bitnami/spark` and this would be the recommended way to solve it. An alternative would be to run the container as root, though it is not advisable.

Thanks @FraPazGal , I would love to test it out. How do we do this using Helm Charts?

**Comment by OneCricketeer** [comment]
> using Helm Charts

Create a persistent volume with JARs or add them to a custom image like you're already doing

**Comment by FraPazGal** [comment]
Hello @porscheme,

As explained by @OneCricketeer, you would need to use an initContainer where you will download the `.jar` files and a persistent volume to store said `.jar`. After downloading them, you can mount the used volume in the pod's main container (spark).

If you have any issues applying the solution in our chart, please do not doubt to open a ticker in our `bitnami/charts` repo so we can further help you.

**Comment by porscheme** [comment]
> Hello @porscheme,
> 
> As explained by @OneCricketeer, you would need to use an initContainer where you will download the `.jar` files and a persistent volume to store said `.jar`. After downloading them, you can mount the used volume in the pod's main container (spark).
> 
> If you have any issues applying the solution in our chart, please do not doubt to open a ticker in our `bitnami/charts` repo so we can further help you.

Thanks @FraPazGal  and @OneCricketeer for the reply.

1. Does it mean your official documentation for additional JAR files doesn't work or did I mis understand the docs? Below is an extract from the [docs](https://github.com/bitnami/bitnami-docker-spark)
```
Installing additional jars
By default, this container bundles a generic set of jar files but the default image can be extended to add as many jars as needed for your specific use case. For instance, the following Dockerfile adds [aws-java-sdk-bundle-1.11.704.jar](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bundle/1.11.704):

FROM bitnami/spark
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.704/aws-java-sdk-bundle-1.11.704.jar --o
```
2. Yes, I can try volume approach

**Comment by FraPazGal** [comment]
Hi @porscheme,

Indeed, the current approach explained in the documentation is not working. I have opened an internal task to investigate whether the documentation is obsolete or the approach should still be valid and we need to make some changes to the container. I'll leave this ticket `on-hold` so we can notify any news regarding this in the future.

**Comment by carrodher** [comment]
We are going to transfer this issue to `bitnami/containers`

In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`.

Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
