### ISSUE TITLE
How to connect spark running in docke from my local jupyter lab

### ISSUE THREAD

**Issue by technqvi** [bitnami/bitnami-docker-spark#84]
### Name and Version

spark 3.2.1

### What steps will reproduce the bug?

I am new to docker and spark
I composed docker  as the following command:  docker-compose up 
 the below is  docker-compose.yml

```
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - ".:/test-files:rw"       
       
  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
```
Spark is running in window docker desktop as figure below. and my python eviroment install pyspark as [this link ](https://pypi.org/project/pyspark/)

I found the error as below, How can I code to connect spark in this container docker
  this error is the same as this issue 
[https://github.com/bitnami/bitnami-docker-spark/issues/5](https://github.com/bitnami/bitnami-docker-spark/issues/5)

the last 2 pictures are my spark while running on docker,  I can acces Spark master web ui  http://localhost:8080/

<img width="941" alt="image" src="https://user-images.githubusercontent.com/38780060/170737350-fb790764-6826-4c0f-9a7a-fa2e3c112419.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/38780060/170737794-5e7da17c-a5e5-481a-9ebc-17802e3ffc3c.png">

Thank you.
Pongthorn

### What is the expected behavior?

this is my error code. it is very simple.
```
import pyspark
#sc = pyspark.SparkContext(master="spark://6aaae328cf2f:7077")

sc = pyspark.SparkContext(master="spark://6aaae328cf2f:7077", appName="maps_and_lazy_evaluation_example")
```

### What do you see instead?

it is  error
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [20], in <cell line: 4>()
      1 import pyspark
      2 #sc = pyspark.SparkContext(master="spark://6aaae328cf2f:7077")
----> 4 sc = pyspark.SparkContext(master="spark://6aaae328cf2f:7077", appName="maps_and_lazy_evaluation_example")

File D:\ProgramData\Anaconda3\envs\myexp_base1\lib\site-packages\pyspark\context.py:146, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    144 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    145 try:
--> 146     self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,
    147                   conf, jsc, profiler_cls)
    148 except:
    149     # If an error occurs, clean up in order to allow future SparkContext creation:
    150     self.stop()

File D:\ProgramData\Anaconda3\envs\myexp_base1\lib\site-packages\pyspark\context.py:209, in SparkContext._do_init(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, jsc, profiler_cls)
    206 self.environment["PYTHONHASHSEED"] = os.environ.get("PYTHONHASHSEED", "0")
    208 # Create the Java SparkContext through Py4J
--> 209 self._jsc = jsc or self._initialize_context(self._conf._jconf)
    210 # Reset the SparkConf to the one actually used by the SparkContext in JVM.
    211 self._conf = SparkConf(_jconf=self._jsc.sc().conf())

File D:\ProgramData\Anaconda3\envs\myexp_base1\lib\site-packages\pyspark\context.py:329, in SparkContext._initialize_context(self, jconf)
    325 def _initialize_context(self, jconf):
    326     """
    327     Initialize SparkContext in function to allow subclass specific initialization
    328     """
--> 329     return self._jvm.JavaSparkContext(jconf)

File D:\ProgramData\Anaconda3\envs\myexp_base1\lib\site-packages\py4j\java_gateway.py:1585, in JavaClass.__call__(self, *args)
   1579 command = proto.CONSTRUCTOR_COMMAND_NAME +\
   1580     self._command_header +\
   1581     args_command +\
   1582     proto.END_COMMAND_PART
   1584 answer = self._gateway_client.send_command(command)
-> 1585 return_value = get_return_value(
   1586     answer, self._gateway_client, None, self._fqn)
   1588 for temp_arg in temp_args:
   1589     temp_arg._detach()

File D:\ProgramData\Anaconda3\envs\myexp_base1\lib\site-packages\py4j\protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.NullPointerException
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:78)
	at org.apache.spark.storage.BlockManager.initialize(BlockManager.scala:518)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:596)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Unknown Source)
```

### Additional information

I run docker on Window 10 Enterprise.

**Comment by marcosbc** [comment]
Hi @technqvi, your issue seems to be related to your `pyspark` installation, not to the Spark container image.

[This StackOverflow page](https://stackoverflow.com/questions/70192980/error-creating-sparkcontext-locally-an-error-occurred-while-calling-none-org-apa) seems to recommend reviewing your JRE/JDK installation, as it may not be using the recommended version.
